// Code generated by Prismic. DO NOT EDIT.

import CardGrid from "./CardGrid";
import Hero from "./Hero";
import ResourceLinks from "./ResourceLinks";

export const components = {
	card_grid: CardGrid,
	hero: Hero,
	resource_links: ResourceLinks
};